### ISSUE TITLE
G4_WATER defined in a materials file

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/opengate#108]
In the test data, there are four material database files that contain a line that (re)defines G4_WATER. Fortunately, opengate handles this correctly (ignoring it, but issuing a warning). But I think it would be good to remove those lines. The data files are:

```
./data/gate/gate_test044_pbs/data/HFMaterials2014.db
./data/gate/gate_test042_gauss_gps/data/HFMaterials2014.db
./data/gate/gate_test044_pbs_rot_transl/data/HFMaterials2014.db
./data/gate/gate_test044_pbs_unFocused/data/HFMaterials2014.db

```

These files are not here on github (otherwise I could have simply made a PR for this) but on the in2p3 gitlab server, hence this issue.

**Comment by tbaudier** [comment]
Done with https://github.com/OpenGATE/opengate/pull/133
