### ISSUE TITLE
Downloading / updating G4 data

### ISSUE THREAD

**Issue by nkrah** [OpenGATE/opengate#129]
I just banged my had head for a moment because my simulation would not start because opengate could not find the G4 data files. Sure enough, the files in core/opengate_core/geant4_data were outdated. I think, what had happened is: I pulled a new version of opengate into my local repo with new paths set in the g4DataPath dictionary in g4DataSetup.py. The simulation then looks for data in these paths, but does not find them. The check_G4_data_folder function, which is in __init__.py in opengate_core and thus called upon "import opengate_core" finds the geant4_data folder, but does not detect that the subfolders are outdated. Therefore, the G4 data is not updated. 

I propose to refine the check_G4_data_folder function to actually check the subfolders against the g4DataPath dictionary. 

If there are no objections, I will create a PR for this in the next days.

**Comment by dsarrut** [comment]
yes indeed! The way the g4 data is managed is not optimal.  
However, a warning: the check is performed during the import, so if the check takes time, it may delay the starting phase of **all** scripts (currently, the import phase is already "slow", mainly due to itk I think). 
Please, go with the PR ;) !

**Comment by nkrah** [comment]
Agree, but don't think the check takes time. Downloading data is slow, but that only occurs once in a while after an update. I'll implement and check.

**Comment by nkrah** [comment]
Is there any reason not to get the data from the Geant4 installation which is required anyhow? Does it need to be downloaded separately? By looking up the Geant4 install, one would automatically align G4 and opengate in terms of G4 data. 
Opinions?

**Comment by tbaudier** [comment]
Hi @nkrah 

You're right when you compile opengate. But when you install opengate on your compute with `pip install opengate` , Geant4 is not installed on your computer. You need to download the data.

**Comment by nkrah** [comment]
I see. But don't you need Geant4 even if you install opengate via pip? Opengate uses Geant4 to run the simulation. Or does pip pull a pre-compiled Geant4?

**Comment by tbaudier** [comment]
Inside the wheel of opengate_core, you can find the g4 librairies. But we cannot insert the data into the wheel because they are too big. This is why we prefer to download them at first import of opengate_core. It's not perfect because, the data are not removed correctly with `pip uninstall opengate`

**Comment by nkrah** [comment]
OK, now I got the full picture. 

Is it possible to write a "hook" for the uninstall to remove the data? Possibly also when running an update via pip?

**Comment by tbaudier** [comment]
I have a look and it seems not, eg:
https://stackoverflow.com/questions/70321823/deleting-associated-data-from-a-pip-package-when-uninstalling

**Comment by nkrah** [comment]
In any case, one could consider deleting old G4data when downloading new data upon the import statement after an update.

**Comment by nkrah** [comment]
I am finalizing a PR to solve this issue.

**Comment by tbaudier** [comment]
Done with https://github.com/OpenGATE/opengate/pull/132

**Comment by nkrah** [comment]
Sorry, I re-open this because I created another PR with some improvements over the previous one. Thomas was too efficient ... ;-)
