### ISSUE TITLE
Name space and imports

### ISSUE THREAD

**Issue by nkrah** [OpenGATE/opengate#136]
I open this as issue to keep track of it. 

I think, we should really handle the imports and name space better inside opengate. 
Specifically: The __init__.py in opengate/ include tons of wildcard imports, i.e. from XXX import *. That is considered really bad practice in python and should be avoided, as it mangles up the internal namespace. It also slows down the "import gate" statement tremendously when used in a user script. The reason is, that most modules inside opengate also include an "import gate" statement, so each time the __init__.py in opengate/ is executed. 

I propose to do the following: 
We should go through all modules of opengate and make explicit imports of the objects we need in that module, following the namespace structure (=folder structure) of the opengate package. 

For example: 
the class PhysicsManager (which is defined in opengate/physics/) needs the list object available_additional_physics_lists, which is defined in opengate/physics/. 
Currently, the list is accessed via the global opengate namespace as gate.available_additional_physics_lists. 
It would be much better to do: 
from opengate.physics.helpers_physics import available_additional_physics_lists

In the end, the __init__.py in opengate/ should be empty!

From the users perspective, it is of course nice if it is not necessary to dig in submodules, but the Simulation class anyhow implements many convenience methods which are directly accessed via: 
sim = opengate.Simulation()
sim.XXX

Last point: 
Is there really a strong argument to create a module (=python file) for each class? For example: 
PhysicsManager is defined in PhysicsManager.py. The import following the internal namespace would be: 

from opengate.physics.PhysicsManager import PhysicsManager
but in the module PhysicsManager.py contains nothing else one could import, so there is no point it having it as a module. It wold be better to have: 
from opengate.physics import PhysicsManager

So far my thoughts. Some are to trigger a discussion. Resolving the issue with the wildcard imports, I think, is actually mandatory to fix.

**Comment by dsarrut** [comment]
Fully agree! Just need to find the time to do it ;)

**Comment by nkrah** [comment]
I see. I was actually expecting that. Already amazing how much work you've managed to put into opengate! 
If you want, I'll put the task on my list.

**Comment by dsarrut** [comment]
done #243
