### ISSUE TITLE
Optical Data output number is only number of primaries

### ISSUE THREAD

**Issue by thilomasbaum** [OpenGATE/opengate#158]
Hi!
I'm currently working with Gate9.3 and trying out Optical Simulation with Scintillation processes.
It's working fine thus far, except when I try to generate Optical Data with:

/gate/output/root/setRootOpticalFlag 1

the ROOT Branch only contains Data Points to the number of Primaries, in contrast to the number of actual Optical Photons, which I identified are generated in the crystal using actors and the Hits Collection.

Thank you very much for your hard work!
Kind regards

**Comment by dsarrut** [comment]
Hello, please post the issue in https://github.com/OpenGATE/gate (this repo is for gate future version, optical features are not yet included), thanks
