### ISSUE TITLE
Phase space source not multithreading compatible

### ISSUE THREAD

**Issue by GitFuchs** [OpenGATE/opengate#206]
At the moment the phase space source does not seem to be multithreading compatible.

The issue seems to be how to ensure that multiple processes extract different particles from the phase space file.

I am happy to fix it, but I have no idea how to solve this issue. My knowledge about Geant4 multithreading and its implementation for Gate10 is basically non-existent.

**Comment by dsarrut** [comment]
now it should be ;)

**Comment by nkrah** [comment]
Is this still up to date or can we close it?

**Comment by GitFuchs** [comment]
Dear Nils,

I believe this can be closed.

Best,
Hermann

Am 17. November 2023 10:33:18 MEZ schrieb nkrah ***@***.***>:
>Is this still up to date or can we close it?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenGATE/opengate/issues/206#issuecomment-1816031067
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
DI Hermann Fuchs, PhD
Department of Radiation Oncology
Medical University Vienna
Währinger Gürtel 18-20
A-1090 Wien

Tel. + 43 / 2622 / 26100 / 628
Mail. ***@***.***
