### ISSUE TITLE
opengate_tests error and pycharm error

### ISSUE THREAD

**Issue by HyperionCore** [OpenGATE/opengate#247]
Dears,

I followed the installation guide, while in the opengate_tests, all downloads are finished, but there is error:

/////
Look for tests in: /home/hyperion/anaconda3/envs/vgate/lib/python3.10/site-packages/opengate/tests/../tests/src
The data are not correct in: /home/hyperion/anaconda3/envs/vgate/lib/python3.10/site-packages/opengate/tests/../tests/src/../data
Activate LFS and download them with:
git submodule update --init --recursive
/////
the actual data path is ......../tests/data

and in pycharm
when i import opengate as gate

opengate_core is not detected. Be sure to execute these lines before to run python:
export LD_LIBRARY_PATH=/home/hyperion/anaconda3/envs/vgate/lib/python3.10/site-packages/opengate_core.libs:${LD_LIBRARY_PATH}
export LD_PRELOAD=/home/hyperion/anaconda3/envs/vgate/lib/python3.10/site-packages/opengate_core.libs/libG4processes-92d9f07e.so:/home/hyperion/anaconda3/envs/vgate/lib/python3.10/site-packages/opengate_core.libs/libG4geometry-0c687114.so:${LD_PRELOAD}

**Comment by tbaudier** [comment]
Hi,

For the first problem with the data, It should be ok now if you upgrade opengate:
`pip install --upgrade --pre opengate`

For the PATH issue, copy/paste the output lines in your terminal and run again pycharm from the same terminal
