### ISSUE TITLE
TypeError: 'Box' object is not callable

### ISSUE THREAD

**Issue by HyperionCore** [OpenGATE/opengate#269]
After the upgrade of opengate package, i have error as below:

Traceback (most recent call last):
  File "D:\PycharmProjects\vGate\main.py", line 3, in <module>
    cm = gate.g4_units('cm')
TypeError: 'Box' object is not callable

**Comment by dsarrut** [comment]
yes, the API changed: now you need to use 
`cm = gate.g4_units.cm`
We should update the doc soon

**Comment by nkrah** [comment]
Yes, we definitely should. Sorry about that. We are working on it!

**Comment by HyperionCore** [comment]
thanks！

**Comment by nkrah** [comment]
User doc is updated.
