### ISSUE TITLE
is that possible to provide some demo code to set up a clindricalPET 

### ISSUE THREAD

**Issue by HyperionCore** [OpenGATE/opengate#270]
is that possible to provide some demo code to set up a clindricalPET for the reference. thanks a lot.

**Comment by nkrah** [comment]
Have you checked the code in opengate/contrib/pet?
Is that roughly what you are looking for?

**Comment by HyperionCore** [comment]
@nkrah thanks for the help!

**Comment by nkrah** [comment]
Have you found what you were looking for?

**Comment by nkrah** [comment]
Great. I will close the issue then. 

Just bare in mind that Gate10 is still under active beta development. Some things might break after updates. Just post an issue here and we'll be happy to help out.

**Comment by nkrah** [comment]
Please have a look at test037 and test049
