### ISSUE TITLE
Remove destructors from classes in python

### ISSUE THREAD

**Issue by nkrah** [OpenGATE/opengate#297]
We should remove __del__ methods from the class. Most of them do not do anything and in general it is against common practice in python to implement them unless you really need them. Not a good example to contributors, I think. 

We can always implement a __del__ method if needed for a specific debugging task, but they should not be there by default ...

**Comment by dsarrut** [comment]
I agree: it was for debugging purposes of pickle/unpickle. Now can be removed

**Comment by nkrah** [comment]
Good. will start removing them.

**Comment by nkrah** [comment]
Done. Will be merged with PR #288
