### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/opengate#331]
It's a discussion about the output path:

The output are stored in "output" folder automatically:
https://github.com/OpenGATE/opengate/blob/3cbb30312e9b68a0e8e1c43c6547f2363d2da59c/opengate/managers.py#L1020
and
https://github.com/OpenGATE/opengate/blob/3cbb30312e9b68a0e8e1c43c6547f2363d2da59c/opengate/managers.py#L1180

The idea is good but for the moment, we have some trouble:

- [ ]  "./output" is not compatible with Windows
- [ ]  Not all actors save the output using that system (eg: stats actor)
- [ ] The tests on github actions use absolute paths so the case with relative path is not tested
- [ ] It's not transparent for the user

So, for the release, we chose with @dsarrut to avoid to write "output" and let the user to write the correct output path:
https://github.com/OpenGATE/opengate/pull/332

**Comment by nkrah** [comment]
- Agree with point one - should be easy to fix. 
- True, not all actors use it at the moment. In my mind, we can adapt that when we tackle the actor refactoring in the upcoming weeks. 
- About the github actions, not sure. We should figure out a way to test the relative path. 
- Can you explain what is not transparent? The rule, to be described in the user guide, is: any relative output path provided by the user, including pure filenames, are relative to the simulation's output folder. Only exception: The user provides an absolute path. In that case, this is used without further processing. 

I suggest we discuss this and implement a unified solution when we refactor the actors so they all behave in the same way. What do you think?

**Comment by dsarrut** [comment]
not relevant anymore
