### ISSUE TITLE
Qt6 support

### ISSUE THREAD

**Issue by BishopWolf** [OpenGATE/opengate#338]
Geant4 is moving to qt6 (slowly but moving: https://geant4.web.cern.ch/download/release-notes/notes-v11.2.0.html).

Therefore, Gate should be able to compile in qt6. This means gate_core built against qt6 and all pyqt calls using pyqt6. 
Which version? Obviously the one supported by geant4 but 6.6 should be fine.

**Comment by dsarrut** [comment]
Yes ! We will update the current version to Geant4 11.2 in the following months and look at qt6 at that moment. 
Currently, the qt support within opengate is not working well. Maybe it will be better with qt6 !

**Comment by pavelToman** [comment]
Hello @tbaudier,
thank you for a quick reply!

My sources are for v10.0.2 from https://github.com/OpenGATE/opengate/archive/refs/tags/10.0.2.tar.gz
So I will fetch the master instead :)
