### ISSUE TITLE
Coincidence sorter

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/opengate#406]
The PR https://github.com/OpenGATE/opengate/pull/402 was merged but the test is not totally ok:

test072_1keepAll does not seem specific : if the time window value is modified, there is no difference. Maybe change the initial data with an increased activity rate to be able to see the influence of the time window?
(please keep this PR)

@kochebina

**Comment by kochebina** [comment]
@tbaudier, the tests are completely changed. Please, see PR:  https://github.com/OpenGATE/opengate/pull/410
