### ISSUE TITLE
wget fails to download Geant4/test data

### ISSUE THREAD

**Issue by ndepauw** [OpenGATE/opengate#428]
[Decided to give opengate a shot after the ICCR presentation.]

The whole python install is awesome, that's why I wanted to try, but the `opengate_tests` command would fail to run because the connection keeps crashing during download (might be flagging through the hospital network).
Anyway, I looked more into it, and there is no equivalent of `wget -c` (keep trying to download) in the python implementation.

For now, my workaround was to run `wget -c` manually on all the files, then hijack the wget command in the execution file (opengate_env/lib/python3.11/site-packages/opengate_core/g4DataSetup.py), and replace the `wget.download(package, out=dataLocation)` command with `packageArchive = package.split("/")[-1]`.

As I am typing this, the same issue happened with the test data while downloading.

**Comment by dsarrut** [comment]
Done in #429
