### ISSUE TITLE
DoseActor does not seems to work in MT anymore 

### ISSUE THREAD

**Issue by dsarrut** [OpenGATE/opengate#508]
:cry: 

It means tests are not robust enough

**Comment by andiresch** [comment]
does it mean, that we need an additional and sensitive test case - as next step?

**Comment by nkrah** [comment]
we could, by I think the issue will be resolved within a week or so when we switch to atomic double implementation because that will make the actor intrinsically thread-safe. I have an old branch that I used for extensive tests  this spring - I guess you remember. I reviewed it these days and it will be simple implement the changes in the current code. Based on that, we can put together a reasonable test that is maximally sensitive to concurrent writing in the dose map. 

@andiresch : Do you have a test scenario on mind?

**Comment by andiresch** [comment]
When I changed to thread local images/1darray, low resolution images were the ones with most concurrency problems (ok that's trivial). I used to have a test case with multiple identical simulations (proton beam on water,  same seed,  number threads = number of avail cores ) but with different resolution. The sum of edep should be the same for all. Note: use a 1d resolution along beam direction to increase probability of problems. 
I can provide the test case coming week if you find it useful

**Comment by nkrah** [comment]
Yes, good idea. 1d dose profiles with large spacing and small step limiter to provoke concurrent writing in the same voxels.

**Comment by BishopWolf** [comment]
> You are right. I was (knowingly) negligent about the mutexes in my consolidation PR. Knowingly because I think we will very quickly switch to atomic doubles.

Are you using atomics library ? https://pypi.org/project/atomics/

**Comment by nkrah** [comment]
Thanks for pointing to the libraries. We are using none of the two really because the code in question is in C++. Just plain atomic types from the std library.

**Comment by BishopWolf** [comment]
> Thanks for pointing to the libraries. We are using none of the two really because the code in question is in C++. Just plain atomic types from the std library.

In this case, remember to guard the std::atomic<double> operations in helper functions like this one
```c
std::atomic<double> foo{0};

void add_to_foo(double bar) {
  auto current = foo.load();
  while (!foo.compare_exchange_weak(current, current + bar));
}
```

**Comment by nkrah** [comment]
Yes, exactly. In our prototype we are using this kind of CAS loop.

**Comment by nkrah** [comment]
PR #520 fixes MT for dose-like actors via muteness (as before). 
I put the mutex statements into scopes to minimize their impact on other parts of the code.

**Comment by nkrah** [comment]
DoseActor, LETActor, FluenceActor, TLEDoseActor now have mutexes and are therefore thread-safe.
I'll close the issue.
