### ISSUE TITLE
Time interval function

### ISSUE THREAD

**Issue by majacquet** [OpenGATE/opengate#514]
It seems that for  multiple run simulation, We need to first fill the sim.run_timing_intervals, and then add_dynamic_parameters. The opposite way to behave creates an error

**Comment by nkrah** [comment]
I created PR #518 to address this. The check should be performed only at initialization, not when the simulation is constructed in the user script. The order of commands in the user script should indeed not matter.

**Comment by nkrah** [comment]
Should be fixed with PR ##518 that is now merged into master.
