### ISSUE TITLE
Various issues with test081_simulation_optigan_with_random_seed.py

### ISSUE THREAD

**Issue by alexis-pereda** [OpenGATE/opengate#536]
Tested on Ubuntu 22.04, master branch at the time (commit 6cd98).

Issue 1:
Executing test `test081_simulation_optigan_with_random_seed.py` creates 3 files at current location:
- gate;
- os;
- tu.

It seems related to the imports of the script.

Issue 2:
I ran it on a computer with an X server, using XFCE, and it does something strange with the mouse cursor.
If I click repeatedly (anywhere), it quits with an error:

```
./opengate/tests/src/test081_simulation_optigan_with_random_seed.py: 8: from: not found
./opengate/tests/src/test081_simulation_optigan_with_random_seed.py: 13: Syntax error: "(" unexpected (expecting "then")
```

**Comment by dsarrut** [comment]
the line: 
`#!/usr/bin/env python3 
`
is missing at the beginning ... try `python test081_simulation_optigan_with_random_seed.py`

**Comment by alexis-pereda** [comment]
Oh, you are right, I was too used to the presence of the shebang.
Sorry for that.
