### ISSUE TITLE
Part of the documentation was removed?

### ISSUE THREAD

**Issue by MaxTousss** [OpenGATE/opengate#563]
Just discovered that the documentation for [how to use acolinearity](https://github.com/MaxTousss/opengate/blob/4e52ac713b0bf4851ef2c5974cd20ce851add3f6/docs/source/user_guide_2_3_physics.md) was [replaced by... something funny...](https://github.com/OpenGATE/opengate/blob/8e7c791dec1174df99130110f5a51ecf75513e5c/docs/source/user_guide/user_guide_physics.rst?plain=1#L103)

Git blame says that the current version was from the following [commit](https://github.com/OpenGATE/opengate/commit/18c3154a2ae075bc20f710b7b117bd361be8ffe1). However, since the commit is a switch from markdown to rst, it might have happened earlier.

My question is the following: was this change voluntary? If not, there might be other instances where the documentation was modified incorrectly...

**Comment by dsarrut** [comment]
(and we are currently trying to put back other issues that may arise)

**Comment by MaxTousss** [comment]
I see that your PR added the acolinearity part but not the scintillation part. Was the latter placed somewhere else?

**Comment by dsarrut** [comment]
several parts were removed by mistake, we are looking at it. For the scintillation, you mean this section:  
https://github.com/OpenGATE/opengate/blob/c891c3b2c4ad2e790f13d450dbda1212e45fda53/docs/source/user_guide/user_guide_physics.md#scintillation ? 
Please wait for the #571 to be merged. Then we will add what was removed.
(sorry again!)

**Comment by nkrah** [comment]
Sorry again for the mess. The part got lost while we restructured the doc and converted from md to rst. I just put things back via PR #576. 

@MaxTousss Can you please have a look and check that this is now complete? 

I am not sure if we need to restructure the part on optical physics a bit or adjust the heading levels. But we can do that later.

**Comment by MaxTousss** [comment]
I confirm that the part about acolinearity is okay. As for the rest (e.g., optical physics), I have no idea: it seems that the content was changed since the last time I looked at it so I am unable to confirm nor infirm if everything is there.
