### ISSUE TITLE
Installation of Gate 10 on Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by imbeatriz** [OpenGATE/opengate#638]
Hi everyone!

I am trying to install Gate 10 on my Ubuntu 24.04.1 LTS system. I am facing issues related to the opengate_tests. I followed the instructions on the github page related with the error I am encontering which is “cannot allocate memory in static TLS block”. I added the export GLIBC_TUNABLES=glibc.rtld.optional_static_tls=2000000 line but still when I run the tests I get the same error message for the following tests:

Summary fail: 14/200 failed the tests:
test031_beta_plus_spectrum.py : failed
test059_tpsource_optics_vbl.py : failed
test081_simulation_optigan_with_random_seed.py : failed
test052_tac_activity_source.py : failed
test060_phsp_source_particletype_fromphs_pdgcode.py : failed
test060_phsp_source_until_next_primary.py : failed
test060_phsp_source_translation.py : failed
test081_tle_2_vox.py : failed
test075_siemens_cios_alpha.py : failed
test051_adder_time_difference.py : failed
test015_iec_phantom_1.py : failed
test060_phsp_source_particletype_direct.py : failed
test060_phsp_source_rotation.py : failed
test058_iec_six_spheres.py : failed
Oh no, not all tests passed.
Evaluation took in total:     6.7 min  
False

I tried using the other option: export LD_PRELOAD=<path to libG4processes>:<path to libG4geometry>:${LD_PRELOAD} but I can't seem to find those libraries.

Does anyone know how I could solve this?

Thank you in advance!

Ps. I have python version 3.12.3

**Comment by tbaudier** [comment]
Hello @imbeatriz 

You almost found the solution using LD_PRELOAD but you need to set the paths to libG4processes and libG4geometry:

```
export LD_LIBRARY_PATH=<path to python env>/lib/python3.12/site-packages/opengate_core.libs:${LD_LIBRARY_PATH}

export LD_PRELOAD=<path to python env>/lib/python3.12/site-
packages/opengate_core.libs/libG4processes.so:<path to python env>/lib/python3.12/site-
packages/opengate_core.libs/libG4geometry.so
```
You need to adapt the path to your installation.

If it still does not work, could you copy paste all the output please?

**Comment by imbeatriz** [comment]
Hi @tbaudier 

It worked now. Thank you!!

**Comment by ParisaNaghdi** [comment]
I have the same problem I did all things you mentioned above but there are a lot of them some tests which are failed.

e
